name: 'Testing Go App'
runs:
  using: "composite"
  steps:
    - name: Checkout ${{ github.event.repository.name }} repo
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.repository.name }}
    - name: Checkout backend-services repo
      uses: actions/checkout@v3
      with:
        repository: getalternative/backend-services
        token: ${{ secrets.ACCESS_TOKEN }}
        persist-credentials: false
        fetch-depth: 0
        path: backend-services
    - run: tar zxvf cockroach.linux-amd64.tgz
      working-directory: ./backend-services
    
    - uses: actions/setup-go@v3
      with:
        go-version: "1.19"
    - run: git config --global url."https://fernandobandeira:${{ secrets.ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
    - run: go env -w GOPRIVATE=github.com/getalternative
    - run: go mod download
      working-directory: ./${{ github.event.repository.name }}
    - name: Run Tests
      run: COCKROACH_BINARY="../backend-services/cockroach.linux-amd64/cockroach" make test-ci
      working-directory: ./${{ github.event.repository.name }}
    - name: Upload coverage
      run: |
        export CODACY_API_TOKEN=${{ secrets.CODACY_API_TOKEN }}
        export CODACY_ORGANIZATION_PROVIDER=${{ secrets.CODACY_ORGANIZATION_PROVIDER }}
        export CODACY_USERNAME=${{ secrets.CODACY_USERNAME }}
        export CODACY_PROJECT_NAME=${{ github.event.repository.name }}
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r coverage.txt
      working-directory: ./${{ github.event.repository.name }}