name: 'Testing Go App'
inputs:
  access-token:
    description: 'Gthub Token to access private repositories'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout ${{ github.event.repository.name }} repo
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}
        token: ${{ inputs.access-token }}

    - name: Checkout backend-services repo
      uses: actions/checkout@v4
      with:
        repository: getalternative/backend-services
        token: ${{ inputs.access-token }}
        persist-credentials: false
        fetch-depth: 0
        path: backend-services

    - name: Setup CockroachDB
      run: tar zxvf cockroach.linux-amd64.tgz
      shell: bash
      working-directory: ./backend-services
    
    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
        cache-dependency-path: "**/*.sum"

    - name: Move to the repo
      run: cd ${{ github.event.repository.name }}
      shell: bash

    - name: Install Go dependencies
      run: |
        git config --global url."https://fernandobandeira:${{ inputs.access-token }}@github.com".insteadOf "https://github.com"
        go env -w GOPRIVATE=github.com/getalternative
        go mod download
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      shell: bash

    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        version: "24.3"

    - name: Run Generate
      run: go generate ./...
      shell: bash

    - uses: stefanzweifel/git-auto-commit-action@v4

    - name: Check changes
      if: steps.auto-commit-action.outputs.changes_detected == 'false'
      run: |
        echo "Changes detected, stop test"
        exit 1

    - name: Run Tests
      run: COCKROACH_BINARY="../backend-services/cockroach.linux-amd64/cockroach" make test-ci
      shell: bash
