name: 'Generate Go App'
inputs:
  access-token:
    description: 'Gthub Token to access private repositories'
    required: true
runs:
  using: "composite"
  # if: github.ref == 'refs/heads/renovate/entgo.io-ent-0.x' || github.ref == 'refs/heads/renovate/google.golang.org-grpc-1.x' || github.ref == 'refs/heads/renovate/github.com-99designs-gqlgen-0.x'
  steps:
    - name: Checkout ${{ github.event.repository.name }} repo
      uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    - name: Install Go dependencies
      run: |
        git config --global url."https://fernandobandeira:${{ inputs.access-token }}@github.com".insteadOf "https://github.com"
        go env -w GOPRIVATE=github.com/getalternative
        go mod download
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      shell: bash
    - name: Run Generate
      run: go generate ./...
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
